name: timer_app
description: A new Flutter project. 
publish_to: 'none'   
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^0.1.3
  flutter_bloc: ^4.0.0
  equatable: ^1.0.0
  wave: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
 
  uses-material-design: true

  
  # assets:
  #   - images/ 