name: flutter_cointopper
description: A new Flutter project.

 
publish_to: 'none' 
 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^0.1.3
  hexcolor: ^1.0.4
  font_awesome_flutter: ^8.8.1
  youtube_player_flutter: ^7.0.0+7
  carousel_slider: ^2.3.1
  sticky_headers: "^0.1.8"
  responsive_table: ^0.1.1+8
  lazy_data_table: ^0.1.5
  table_sticky_headers: ^1.1.2
  horizontal_data_table: ^1.0.6+3
  bloc: ^6.1.0
  flutter_bloc: ^6.1.0
  equatable: ^1.2.5
  http: ^0.12.2
  intl: ^0.16.1
  loadmore: ^1.0.4
  url_launcher: ^5.7.10 
  flutter_typeahead: ^1.8.8
  autocomplete_textfield: ^1.6.4
  incrementally_loading_listview: ^0.3.0
  webview_flutter: ^1.0.7
  flutter_webview_plugin: ^0.3.11
  rflutter_alert: ^1.0.3
  image_picker_saver: ^0.3.0
  fl_chart: ^0.12.1
  syncfusion_flutter_datagrid: ^18.4.30
  infinite_scroll_pagination: ^2.3.0
  readmore: ^1.0.1
  flutter_sparkline: ^0.1.0
  flutter_widget_from_html_core: ^0.5.2 

dev_dependencies:
  flutter_test:
    sdk: flutter 
flutter:
 
  uses-material-design: true 
  assets:
    - assets/images/ 